# NOTE: update this with your service name
service: nodeRubyLambdas

# Use the serverless-webpack plugin to transpile ES6
plugins:
  # - serverless-webpack
  - serverless-offline
  - serverless-hooks-plugin
custom:
  # webpack:
  #   webpackConfig: ./webpack.config.js
  #   includeModules: true
  hooks:
    package:initialize:
      - bundle install --deployment

provider:
  name: aws
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

  package:
    individually: true

functions:
  nodeMain:
    handler: node/handler.main
    runtime: nodejs8.10
    events:
      - http:
          path: main
          method: get
    package:
      individually: true
      include:
        - node/**
        - handler.js
      exclude:
        - .git/**
        - .travis.yml
  rubyEncryption:
    handler: ruby/rubyRijndaelEncryption.lambda_handler
    runtime: ruby2.5
    environment:
      RIJNDAEL_PASSWORD: 'w4rf2gr9e6lm24bgf1xsd2v'
    package:
      individually: true
      include:
        - vendor/**
        - rubyRijndaelEncryption.rb
      exclude:
        - Gemfile
        - Gemfile.lock
        - Rakefile
        - spec/**
        - node/**
        - node_modules/**
