# NOTE: update this with your service name
service: nodeLambdas

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-hooks-plugin
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  # hooks:
  #   package:initialize:
  #     - bundle install --deployment
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  stage: dev
  region: us-west-2
  # environment:
  #   rubyEncryptionLambda:
  #     - 'Fn::ImportValue': ${self:custom.stage}-rubyEncryptionArn
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - 'Fn::ImportValue': rubyEncryption
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  #environment: ${file(env.yml):${self:provider.stage}}

  package:
    individually: true

functions:
  nodeMain:
    handler: node/handler.main
    runtime: nodejs8.10
    events:
      - http:
          path: main
          method: get
